version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    container_name: zookeeper

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    container_name: kafka

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    container_name: mongodb

  logistics:
    build:
      context: .
      dockerfile: Dockerfile.logistics
    depends_on:
      - kafka
      - mongodb
    ports:
      - "9090:9090" # Port where the logistics service will run

  standard:
    build:
      context: .
      dockerfile: Dockerfile.standard
    depends_on:
      - kafka
      - mongodb
    ports:
      - "9091:9091" # Port where the standard delivery service will run

  express:
    build:
      context: .
      dockerfile: Dockerfile.express
    depends_on:
      - kafka
      - mongodb
    ports:
      - "9092:9092" # Port where the express delivery service will run

  international:
    build:
      context: .
      dockerfile: Dockerfile.international
    depends_on:
      - kafka
      - mongodb
    ports:
      - "9093:9093" # Port where the international delivery service will run

volumes:
  mongo_data:
