# Use the official Ballerina image
FROM ballerina/ballerina:slp4

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the logistics service Ballerina code into the container
COPY ./src/logistics_service .

# Expose the port where the logistics service will be running
EXPOSE 9090

# Command to run the Ballerina logistics service when the container starts
CMD ["ballerina", "run", "logistics_service.bal"]
